FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY src ./src

ENV PORT=4001
EXPOSE 4001

CMD ["sh", "-c", "if [ \"$DEV_MODE\" = \"true\" ]; then ./node_modules/.bin/nodemon --watch src --delay 1 --exec \"npm run start:replica\"; else npm run start:replica; fi"]